name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  file-to-execute:  # id of input
    description: 'the file to launch'
    required: true
  options:
    description: 'options to launch in nbconvert'
    required: true
    default: ''
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}
    